### ISSUE TITLE
Small dataset for testing

### ISSUE THREAD

**Issue by biddisco** [WietseWind/fetch-xrpl-transactions#2]
Would it be possible to make a small dataset, such as an hour/day's worth of ledgers available via direct download to enable testing before taking the plunge and signing up for a 'bigquery' account.

**Comment by WietseWind** [comment]
Here you go, the most recent 10k ledgers (still backfilling, so not the most recent transactions) https://xakurbw.dlvr.cloud

**Comment by biddisco** [comment]
That was quick. Thanks very much. I expected to see a MongoDB file. I will create one from the json and try to make sure I get the layout the same.

**Comment by WietseWind** [comment]
Google BigQuery is in fact schema based allowing SQL-like queries, it isn't mongo (anymore) - or are you talking about the [mongo](https://github.com/WietseWind/fetch-xrpl-transactions/tree/mongodb) branch?

**Comment by biddisco** [comment]
I'm not sure what I meant. I _thought_ that the database in google bigquery was a mongodb one, so I wanted to experiment with some queries on a local database that would be the same. I'm not much of an expert with database stuff (or languages like javascript/nodejs) unfortunately, so I'm learning as I go here.
