### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Silkjaer** [WietseWind/fetch-xrpl-transactions#6]
I have found some duplicates in the BigQuery dataset (transactions with the same hash), example:

```
  SELECT
    *
  FROM
    xrpledgerdata.fullhistory.transactions
  WHERE
    `hash` = "93DA464BB51C01563E6848CFF482A6C84029AF633E711FD881772957A998994B"
```

Maybe a cleanup routine could be made to avoid these (or a constraint on the table, if possible in BQ)?

**Comment by WietseWind** [comment]
I know, some retries happend while (async) the original insert was processed after all. 

BigQuery cannot clean/delete data :( and a lookup before inserts would be to time consuming. And to make it even more complex: some types of transactions may actually have the same hash (like a TX to set the Fee, the same Tx may be submitted on multiple occasions, being identical the hash will be identical.

Easiest "solution" (workaround) is to select distinct.

**Comment by Silkjaer** [comment]
Ouch, well, fairly easy to work around in queries as you say.
