### ISSUE TITLE
No data since 2020-12-23

### ISSUE THREAD

**Issue by shaelilwang** [WietseWind/fetch-xrpl-transactions#9]
It seems that the `transactions` table stopped updating since 12/23. Are there any plans to fix this? Thanks!

**Comment by WietseWind** [comment]
Oops, you are right! So sorry!

Immediately restarted the process, it'll backfill now, and keep the dataset up to date again.

Thanks for the heads up! 🤗

**Comment by shaelilwang** [comment]
Great, thank you!
